name: unit-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Install Dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate();'
      - name: Test package
        run: julia --project -e 'using Pkg; Pkg.test();'
